name: Publish-Game

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{secrets.RELEASE_KEY}}
      REPO: ${{github.event.repository.url}}
      RELEASE_NAME: ${{github.event.payload.push_id}}
    steps:
      - name: Publish Release
        uses: docker://punchcafe/build-gbnvg:0.0.2