name: Publish-Game

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{secrets.RELEASE_KEY}}
      REPO: ${{github.event.repository.url}}
      RELEASE_NAME: ${{github.event.repository.pushed_at}}
    steps:
      - name: Publish Release
        uses: docker://punchcafe/build-gbnvg:0.0.2